# Generated by Django 3.2.7 on 2021-10-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Никнейм')),
                ('state', models.CharField(blank=True, max_length=32, null=True, verbose_name='Статус чата')),
                ('last_active_date', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
    ]
