# Generated by Django 3.2.7 on 2021-10-04 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Никнейм')),
                ('last_active_date', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя состояния')),
            ],
            options={
                'verbose_name': 'Статус состояния',
                'verbose_name_plural': 'Статусы состояния',
            },
        ),
        migrations.CreateModel(
            name='StateToBotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_data', models.CharField(max_length=64, verbose_name='Информация о состоянии')),
                ('bot_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='users.botuser', verbose_name='Пользователь')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='users.state', verbose_name='Статус сотсояния')),
            ],
            options={
                'verbose_name': 'Статус состояние к состоянию',
                'verbose_name_plural': 'Статус состояния к состояниям',
            },
        ),
    ]
