# Generated by Django 3.2.7 on 2021-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='prev_state',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Предыдущий статус чата'),
        ),
    ]
