# Generated by Django 3.2.7 on 2021-10-02 12:04

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
                ('start_date', models.DateTimeField(verbose_name='Время начала')),
                ('end_date', models.DateTimeField(verbose_name='Время окончания')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='Задача просрочена')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Задача завершена')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('members', models.ManyToManyField(related_name='tasks', to='projects.ProjectRole', verbose_name='Участники')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskConfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(blank=True, null=True, verbose_name='Проверена')),
                ('comment', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Комментарий')),
                ('checked_date', models.DateTimeField(blank=True, null=True, verbose_name='Проверена')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirms_checked', to='projects.projectrole', verbose_name='Проверяющий')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirms_created', to='projects.projectrole', verbose_name='Исполнитель')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Подтверждение задачи',
                'verbose_name_plural': 'Подтверждения задач',
            },
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('UP', 'Запланирована'), ('IP', 'В работе'), ('DN', 'Выполнена'), ('CL', 'Отменена')], max_length=2, verbose_name='Статус')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Время начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Время конца')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Статус задачи к задаче',
                'verbose_name_plural': 'Статусы задачи к задачам',
            },
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tasks.models.task_directory_path)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.task', verbose_name='К задаче')),
            ],
            options={
                'verbose_name': 'Файл к задаче',
                'verbose_name_plural': 'Файлы к задачам',
            },
        ),
        migrations.CreateModel(
            name='TaskConfirmFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=50, verbose_name='ID файла телеграм')),
                ('file_type', models.CharField(max_length=10, verbose_name='Тип файла')),
                ('task_confirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tasks.taskconfirm', verbose_name='К подтверждению задачи')),
            ],
            options={
                'verbose_name': 'Файл к подтверждению задачи',
                'verbose_name_plural': 'Файлы к подтверждению задач',
            },
        ),
        migrations.CreateModel(
            name='Refinement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=3000, verbose_name='Описание')),
                ('new_end_date', models.DateTimeField(verbose_name='Время окончания')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refinements', to='tasks.task', verbose_name='К задаче')),
            ],
            options={
                'verbose_name': 'Доработка',
                'verbose_name_plural': 'Доработки',
            },
        ),
        migrations.CreateModel(
            name='Postponement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_start_date', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('new_end_date', models.DateTimeField(verbose_name='Время окончания')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postponements', to='tasks.task', verbose_name='К задаче')),
            ],
            options={
                'verbose_name': 'Отсрочка',
                'verbose_name_plural': 'Отсрочки',
            },
        ),
    ]
